### ISSUE TITLE
I encountered an error

### ISSUE THREAD

**Issue by 19931205** [lingeringlight/ALOFT#2]
Firstly, I encountered some path errors and used absolute paths to solve them. Now, there is an error that I don't know how to handle.

Test:  [ 0/14]  eta: 0:00:19  loss: 0.3078 (0.3078)  acc1: 93.7500 (93.7500)  acc5: 100.0000 (100.0000)  time: 1.4198  data: 0.3797  max mem: 874
Test:  [13/14]  eta: 0:00:00  loss: 0.2007 (0.1916)  acc1: 96.8750 (96.9158)  acc5: 100.0000 (100.0000)  time: 0.1531  data: 0.0272  max mem: 874
Test: Total time: 0:00:02 (0.1596 s / it)
Test: Total time: 0:00:00 (27794742.5842 s / it)
Traceback (most recent call last):
  File "main_gfnet.py", line 636, in <module>
    main(args)
  File "main_gfnet.py", line 490, in main
    test_stats = evaluate(data_loader_test, model, device)['acc1']
KeyError: 'acc1'

**Comment by lingeringlight** [comment]
Hi, it appears that the issue you have encountered may have been caused by some unintentional bugs that were introduced during modification, and we are unable to reproduce them. You might want to consider checking the "evaluate" function in the "engine.py" file or directly re-downloading the source code to resolve this issue. 

I hope this helps! Let me know if you have any further questions.
